sudo: required
os: osx
language: swift
osx_image: xcode9.2
node_js: 9
# xcode_project: StellarKit.xcodeproj
# xcode_scheme: StellarKit
xcode_sdk: iphonesimulator

before_script:
  - brew update && brew install libsodium
  # - git clone https://github.com/kinfoundation/travis-stellar-core-macos.git
  # - cd travis-stellar-core-macos && ./setup.sh && cd ..
  # - ./travis-stellar-core-macos/stellarcmd/stellarcmd -c ./travis-stellar-core-macos/stellarcmd/config.json info GCLBBAIDP34M4JACPQJUYNSPZCQK7IRHV7ETKV6U53JPYYUIIVDVJJFQ
  # - ./travis-stellar-core-macos/stellarcmd/stellarcmd -c ./travis-stellar-core-macos/stellarcmd/config.json create GBSJ7KFU2NXACVHVN2VWQIXIV5FWH6A7OIDDTEUYTCJYGY3FJMYIDTU7
  # - ./travis-stellar-core-macos/stellarcmd/stellarcmd -c ./travis-stellar-core-macos/stellarcmd/config.json info GBSJ7KFU2NXACVHVN2VWQIXIV5FWH6A7OIDDTEUYTCJYGY3FJMYIDTU7

#Install appium
  - brew upgrade openssl
  - brew upgrade python
  #Installs GNU grep
  - brew install grep
  - npm install -g appium
  - npm install -g wd
  - npm install -g appium-doctor
  - npm install -g ios-webkit-debug-proxy
  
script:
  # - cd /Users/travis/build/jaffamonkey/nightwatch_appium
   - git config lfs.https://github.com/jaffamonkey/nightwatch_appium.git/info/lfs.access basic
  - npm install
  - appium-doctor --ios
  - appium &
  # - ios-webkit-debug-proxy -f http://www.bbc.co.uk &
  - sleep 20
  - npm run e2e-test
