sudo: required
os: osx
language: objective-c
node_js: '9'
osx_image: xcode9.3
env: DEVICE=11.2       
rvm: system
  
before_script:
  - brew cask reinstall xquartz
  - brew uninstall carthage
  - brew install carthage
  - brew link --overwrite carthage
  - npm install -g appium
  - npm install -g appium-doctor
  - npm install wd
  
script:
  - npm install
  - appium-doctor --ios
  # - appium &
  - npm run e2e-test
