sudo: required
os: osx
language: objective-c
node_js: '9'
osx_image: xcode9.3
env: DEVICE=11.2       
rvm: system
  
before_script:
  - export DBUS_SESSION_BUS_ADDRESS=/dev/null
  - brew cask reinstall xquartz
  - export DISPLAY=:5.0
  - sudo Xvfb :99 -ac -screen 0 1024x768x8 &
  - brew uninstall carthage
  - brew install carthage
  - brew link --overwrite carthage
  - npm install -g appium
  - npm install -g appium-doctor
  - npm install wd
  
script:
  - npm install
  - appium-doctor --ios
  - appium &
  - sleep 20
  - npm run e2e-test
